version: "3.1" # docker-compose 문서에 대한 버전을 지정
# 버전에 따라 조금씩 기능과 옵션이 다를 수 있다.

services: # 컨테이너를 실행하기 위해 정의함
  mysqqql: #services 내부에 컨테이너의 이름을 지정함 => docker ps하면 나오는 name
    image: mysql # 컨테이너에 사용될 이미지
    container_name: ${CONTAINER_NAME_DB}
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_USER: ${DB_USERNAME_DB}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "${DB_PORT}:5555"
